"""Random initial-condition utilities."""

from __future__ import annotations

from typing import Any

from rmhdgpu.masks import apply_mask


def random_band_limited_field(
    grid: Any,
    backend: Any,
    fft: Any,
    kmin: float,
    kmax: float,
    seed: int | None = None,
    rms: float = 1.0,
    dealias_mask: Any | None = None,
) -> Any:
    """Return a random Fourier field band-limited by total wavenumber magnitude.

    The field is generated by:

    1. drawing a real-valued random field on the active backend
    2. transforming it to `rfftn` storage
    3. zeroing modes outside `kmin <= sqrt(k^2) <= kmax`
    4. inverse transforming back to real space
    5. normalizing to the requested RMS
    6. transforming back to Fourier space

    Band-limiting is done using the total magnitude `sqrt(k2)`, where `k2`
    includes both perpendicular and parallel contributions.
    """

    if kmin < 0.0:
        raise ValueError(f"kmin must be nonnegative; got {kmin}.")
    if kmax <= 0.0 or kmax < kmin:
        raise ValueError(f"kmax must be positive and >= kmin; got kmin={kmin}, kmax={kmax}.")
    if rms <= 0.0:
        raise ValueError(f"rms must be positive; got {rms}.")

    xp = backend.xp
    rng = xp.random.default_rng(seed)

    field_real = rng.standard_normal(grid.real_shape).astype(grid.real_dtype, copy=False)
    field_hat = fft.r2c(field_real)

    k_mag = xp.sqrt(grid.k2)
    band_mask = (k_mag >= kmin) & (k_mag <= kmax)
    apply_mask(field_hat, band_mask)

    if dealias_mask is not None:
        apply_mask(field_hat, dealias_mask)

    field_real = fft.c2r(field_hat)
    current_rms = backend.scalar_to_float(xp.sqrt(xp.mean(field_real**2)))
    if current_rms == 0.0:
        raise ValueError(
            "Band-limiting removed all content from the random field; choose a wider k-range."
        )

    field_real *= (rms / current_rms)
    field_hat = fft.r2c(field_real)

    if dealias_mask is not None:
        apply_mask(field_hat, dealias_mask)

    return field_hat

